PRESIDENTS = [
    "George Washington",
    "John Adams",
    "Thomas Jefferson",
    "James Madison",
    "James Monroe",
    "John Quincy Adams",
    "Andrew Jackson",
    "Martin Van Buren",
    "William Henry Harrison",
    "John Tyler",
    "James K. Polk",
    "Zachary Taylor",
    "Millard Fillmore",
    "Franklin Pierce",
    "James Buchanan",
    "Abraham Lincoln",
    "Andrew Johnson",
    "Ulysses S. Grant",
    "Rutherford B. Hayes",
    "James A. Garfield",
    "Chester A. Arthur",
    "Grover Cleveland",
    "Benjamin Harrison",
    "William McKinley",
    "Theodore Roosevelt",
    "William Howard Taft",
    "Woodrow Wilson",
    "Warren G. Harding",
    "Calvin Coolidge",
    "Herbert Hoover",
    "Franklin D. Roosevelt",
    "Harry S. Truman",
    "Dwight D. Eisenhower",
    "John F. Kennedy",
    "Lyndon B. Johnson",
    "Richard Nixon",
    "Gerald Ford",
    "Jimmy Carter",
    "Ronald Reagan",
    "George H. W. Bush",
    "Bill Clinton",
    "George W. Bush",
    "Barack Obama",
    "Donald Trump",
    "Joe Biden",
]
SECRETARIES_OF_STATE = [
    "John Jay",
    "Thomas Jefferson",
    "Edmund Randolph",
    "Timothy Pickering",
    "Charles Lee",
    "John Marshall",
    "Levi Lincoln Sr.",
    "James Madison",
    "Robert Smith",
    "James Monroe",
    "John Graham",
    "Richard Rush",
    "John Quincy Adams",
    "Daniel Brent",
    "Henry Clay",
    "James Alexander Hamilton",
    "Martin Van Buren",
    "Edward Livingston",
    "Louis McLane",
    "John Forsyth",
    "Jacob L. Martin",
    "Daniel Webster",
    "Hugh S. Legaré",
    "William S. Derrick",
    "Abel P. Upshur",
    "John Nelson",
    "John C. Calhoun",
    "James Buchanan",
    "John M. Clayton",
    "Charles Magill Conrad",
    "Edward Everett",
    "William Hunter",
    "William L. Marcy",
    "Lewis Cass",
    "Jeremiah S. Black",
    "William H. Seward",
    "Elihu B. Washburne",
    "Hamilton Fish",
    "William M. Evarts",
    "James G. Blaine",
    "Frederick Theodore Frelinghuysen",
    "Thomas F. Bayard",
    "William F. Wharton",
    "John W. Foster",
    "Walter Q. Gresham",
    "Edwin F. Uhl",
    "Richard Olney",
    "John Sherman",
    "William R. Day",
    "Alvey A. Adee",
    "John Hay",
    "Francis B. Loomis",
    "Elihu Root",
    "Robert Bacon",
    "Philander C. Knox",
    "William Jennings Bryan",
    "Robert Lansing",
    "Frank Polk",
    "Bainbridge Colby",
    "Charles Evans Hughes",
    "Frank B. Kellogg",
    "Henry L. Stimson",
    "Cordell Hull",
    "Edward Stettinius Jr.",
    "Joseph Grew",
    "James F. Byrnes",
    "George C. Marshall",
    "Dean Acheson",
    "H. Freeman Matthews",
    "John Foster Dulles",
    "Christian Herter",
    "Livingston T. Merchant",
    "Dean Rusk",
    "Charles E. Bohlen",
    "William P. Rogers",
    "Kenneth Rush",
    "Henry Kissinger",
    "Philip Habib",
    "Cyrus Vance",
    "Warren Christopher",
    "David D. Newsom",
    "Richard N. Cooper",
    "Edmund Muskie",
    "Alexander Haig",
    "Walter J. Stoessel Jr.",
    "George Shultz",
    "Michael Armacost",
    "James Baker",
    "Lawrence Eagleburger",
    "Arnold Kanter",
    "Frank G. Wisner",
    "Madeleine Albright",
    "Colin Powell",
    "Condoleezza Rice",
    "William J. Burns",
    "Hillary Clinton",
    "John Kerry",
    "Thomas A. Shannon Jr.",
    "Rex Tillerson",
    "John J. Sullivan",
    "Mike Pompeo",
    "Daniel Bennett Smith",
    "Antony Blinken",
]
